'use client';
import { useState, useEffect } from 'react';
import { useTenant } from '@/core/lib/tenant-context';
interface Props { open: boolean; onClose: () => void; }
type ActiveSection = 'profile' | 'password';
export function ProfileModal({ open, onClose }: Props) {
  const { tenant, updateTenantLocal } = useTenant();
  const [section, setSection] = useState<ActiveSection>('profile');
  const [ownerName, setOwnerName] = useState(''); const [displayName, setDisplayName] = useState(''); const [email, setEmail] = useState('');
  const [profileLoading, setProfileLoading] = useState(false); const [profileMsg, setProfileMsg] = useState<{ type: 'ok' | 'err'; text: string } | null>(null);
  const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState('');
  const [pwLoading, setPwLoading] = useState(false); const [pwMsg, setPwMsg] = useState<{ type: 'ok' | 'err'; text: string } | null>(null);
  useEffect(() => { if (open && tenant) { setOwnerName(tenant.ownerName || ''); setDisplayName(tenant.displayName || ''); setEmail(tenant.email || ''); setProfileMsg(null); setPwMsg(null); setCurrentPassword(''); setNewPassword(''); setConfirmPassword(''); setSection('profile'); } }, [open, tenant]);
  if (!open || !tenant) return null;
  const memberSince = tenant.createdAt ? new Date(tenant.createdAt).toLocaleDateString('pt-BR', { day: '2-digit', month: 'long', year: 'numeric' }) : 'N/A';
  async function handleSaveProfile() { setProfileMsg(null); setProfileLoading(true); try { const res = await fetch('/api/telegram/auth', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'update_profile', tenantId: tenant!.tenantId, ownerName, displayName, email }) }); const data = await res.json(); if (data.success) { updateTenantLocal({ ownerName, displayName, email }); setProfileMsg({ type: 'ok', text: 'Perfil atualizado' }); } else setProfileMsg({ type: 'err', text: data.error || 'Erro ao salvar' }); } catch { setProfileMsg({ type: 'err', text: 'Erro de conexão' }); } finally { setProfileLoading(false); } }
  async function handleChangePassword() { setPwMsg(null); if (newPassword.length < 6) { setPwMsg({ type: 'err', text: 'Nova senha deve ter pelo menos 6 caracteres' }); return; } if (newPassword !== confirmPassword) { setPwMsg({ type: 'err', text: 'As senhas não coincidem' }); return; } setPwLoading(true); try { const res = await fetch('/api/telegram/auth', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'change_password', tenantId: tenant!.tenantId, currentPassword, newPassword }) }); const data = await res.json(); if (data.success) { setPwMsg({ type: 'ok', text: 'Senha alterada com sucesso' }); setCurrentPassword(''); setNewPassword(''); setConfirmPassword(''); } else setPwMsg({ type: 'err', text: data.error || 'Erro ao trocar senha' }); } catch { setPwMsg({ type: 'err', text: 'Erro de conexão' }); } finally { setPwLoading(false); } }
  const tabStyle = (active: boolean): React.CSSProperties => ({ padding: '8px 16px', fontSize: 13, fontWeight: active ? 600 : 500, color: active ? 'var(--accent)' : 'var(--text-secondary)', background: 'none', border: 'none', borderBottomWidth: 2, borderBottomStyle: 'solid', borderBottomColor: active ? 'var(--accent)' : 'transparent', cursor: 'pointer', marginBottom: -1 });
  return (<div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.4)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 200, padding: 20, animation: 'fadeIn 0.15s ease' }} onClick={onClose}>
    <div style={{ background: 'var(--bg-card)', borderRadius: 'var(--radius-xl)', width: '100%', maxWidth: 480, maxHeight: '90vh', display: 'flex', flexDirection: 'column', boxShadow: '0 20px 60px rgba(0,0,0,0.15)', overflow: 'hidden' }} onClick={e => e.stopPropagation()}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '20px 24px 0' }}><h2 style={{ fontSize: 18, fontWeight: 700, color: 'var(--text-primary)', margin: 0, letterSpacing: '-0.02em' }}>Configurações da conta</h2><button onClick={onClose} style={{ width: 32, height: 32, borderRadius: 8, border: 'none', background: 'var(--bg-muted)', color: 'var(--text-secondary)', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer' }}>✕</button></div>
      <div style={{ display: 'flex', gap: 0, padding: '16px 24px 0', borderBottomWidth: 1, borderBottomStyle: 'solid', borderBottomColor: 'var(--border)' }}><button onClick={() => setSection('profile')} style={tabStyle(section === 'profile')}>Perfil</button><button onClick={() => setSection('password')} style={tabStyle(section === 'password')}>Segurança</button></div>
      <div style={{ padding: '20px 24px 24px', overflowY: 'auto' as const, flex: 1 }}>
        {section === 'profile' && <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <div style={{ background: 'var(--bg-muted)', borderRadius: 'var(--radius-md)', padding: '12px 16px', display: 'flex', flexDirection: 'column', gap: 6 }}><div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ fontSize: 12, color: 'var(--text-secondary)' }}>ID da conta</span><span style={{ fontSize: 12, fontWeight: 500, fontFamily: 'var(--font-mono)' }}>{tenant.tenantId.slice(0, 8)}...</span></div><div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ fontSize: 12, color: 'var(--text-secondary)' }}>Membro desde</span><span style={{ fontSize: 12, fontWeight: 500 }}>{memberSince}</span></div></div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}><label style={{ fontSize: 12, fontWeight: 600, textTransform: 'uppercase' as const, letterSpacing: '0.04em' }}>Nome completo</label><input style={{ padding: '10px 14px', fontSize: 14, border: '1px solid var(--border)', borderRadius: 'var(--radius-sm)', outline: 'none' }} value={ownerName} onChange={e => setOwnerName(e.target.value)} /></div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}><label style={{ fontSize: 12, fontWeight: 600, textTransform: 'uppercase' as const, letterSpacing: '0.04em' }}>Nome de exibição</label><input style={{ padding: '10px 14px', fontSize: 14, border: '1px solid var(--border)', borderRadius: 'var(--radius-sm)', outline: 'none' }} value={displayName} onChange={e => setDisplayName(e.target.value)} /></div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}><label style={{ fontSize: 12, fontWeight: 600, textTransform: 'uppercase' as const, letterSpacing: '0.04em' }}>Email</label><input style={{ padding: '10px 14px', fontSize: 14, border: '1px solid var(--border)', borderRadius: 'var(--radius-sm)', outline: 'none' }} type="email" value={email} onChange={e => setEmail(e.target.value)} /></div>
          {profileMsg && <div style={{ fontSize: 13, padding: '10px 14px', borderRadius: 'var(--radius-sm)', ...(profileMsg.type === 'ok' ? { background: 'var(--green-light)', color: 'var(--green)' } : { background: 'var(--red-light)', color: 'var(--red)' }) }}>{profileMsg.text}</div>}
          <button onClick={handleSaveProfile} disabled={profileLoading} style={{ padding: '11px 20px', fontSize: 14, fontWeight: 600, background: 'var(--accent)', color: '#fff', border: 'none', borderRadius: 'var(--radius-sm)', cursor: 'pointer', alignSelf: 'flex-start', opacity: profileLoading ? 0.6 : 1 }}>{profileLoading ? 'Salvando...' : 'Salvar alterações'}</button>
        </div>}
        {section === 'password' && <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <p style={{ fontSize: 13, color: 'var(--text-secondary)', margin: 0 }}>Informe a senha atual e escolha uma nova com pelo menos 6 caracteres.</p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}><label style={{ fontSize: 12, fontWeight: 600, textTransform: 'uppercase' as const }}>Senha atual</label><input style={{ padding: '10px 14px', fontSize: 14, border: '1px solid var(--border)', borderRadius: 'var(--radius-sm)', outline: 'none' }} type="password" value={currentPassword} onChange={e => setCurrentPassword(e.target.value)} /></div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}><label style={{ fontSize: 12, fontWeight: 600, textTransform: 'uppercase' as const }}>Nova senha</label><input style={{ padding: '10px 14px', fontSize: 14, border: '1px solid var(--border)', borderRadius: 'var(--radius-sm)', outline: 'none' }} type="password" value={newPassword} onChange={e => setNewPassword(e.target.value)} /></div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}><label style={{ fontSize: 12, fontWeight: 600, textTransform: 'uppercase' as const }}>Confirmar nova senha</label><input style={{ padding: '10px 14px', fontSize: 14, border: '1px solid var(--border)', borderRadius: 'var(--radius-sm)', outline: 'none' }} type="password" value={confirmPassword} onChange={e => setConfirmPassword(e.target.value)} /></div>
          {pwMsg && <div style={{ fontSize: 13, padding: '10px 14px', borderRadius: 'var(--radius-sm)', ...(pwMsg.type === 'ok' ? { background: 'var(--green-light)', color: 'var(--green)' } : { background: 'var(--red-light)', color: 'var(--red)' }) }}>{pwMsg.text}</div>}
          <button onClick={handleChangePassword} disabled={pwLoading} style={{ padding: '11px 20px', fontSize: 14, fontWeight: 600, background: 'var(--accent)', color: '#fff', border: 'none', borderRadius: 'var(--radius-sm)', cursor: 'pointer', alignSelf: 'flex-start', opacity: pwLoading ? 0.6 : 1 }}>{pwLoading ? 'Alterando...' : 'Alterar senha'}</button>
        </div>}
      </div>
    </div>
  </div>);
}
